#  /* YAML docker-compose.yml configuration file */
  version: "3"
  services:
    db:
      image:  postgres
      restart: always
      ports:
        - "5432:5432"
      environment:
        POSTGRES_PASSWORD: pass123

#  // Start containers in detached / background mode
#  docker-compose up -d
#  docker-compose up <name_of_service> -d

#  // Stop containers
#  docker-compose down
